// <auto-generated />
using System;
using BoardGameHub.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoardGameHub.Data.Migrations
{
    [DbContext(typeof(BoardGameHubDbContext))]
    [Migration("20240406214429_AddApplicationUsers")]
    partial class AddApplicationUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1b572cdb-ca30-43a0-8718-12df99d66c45",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b128cff9-3f18-4d34-8946-2c111d2b7f69",
                            Email = "user@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Ivan",
                            LastName = "Ivanov",
                            LockoutEnabled = false,
                            NormalizedEmail = "user@mail.com",
                            NormalizedUserName = "user@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEKASGe3mq6rGo7frynK2KQggIQt5bfPQc6LdIl9edUyZAQcdBhYHxe/20pNOrcdAdg==",
                            PhoneNumber = "0898888888",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dca7a5cd-f489-4674-aec9-829c4fe47c3e",
                            TwoFactorEnabled = false,
                            UserName = "user@mail.com"
                        },
                        new
                        {
                            Id = "014d16f4-b47d-45fa-98a5-0cb40aa950c5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c1e8224e-12ef-4daa-aca0-c65fa699bb30",
                            Email = "admin@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Zahary",
                            LastName = "Nyagolov",
                            LockoutEnabled = false,
                            NormalizedEmail = "admin@mail.com",
                            NormalizedUserName = "admin@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEDxpuLKL2Dt7O/HRZsntCEDG8hlFTF3cS2+ZrdGMl5MyqHCGCEyNuXhet/buWbtCgA==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f82bb126-5a41-472b-9d2d-75f9a2ce51b6",
                            TwoFactorEnabled = false,
                            UserName = "admin@mail.com"
                        });
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.Boardgame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AppropriateAge")
                        .HasColumnType("int");

                    b.Property<int>("AveragePlayingTime")
                        .HasColumnType("int");

                    b.Property<string>("CardImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("DetailsImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Difficulty")
                        .HasColumnType("float");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUpcoming")
                        .HasColumnType("bit");

                    b.Property<int>("MaximumPlayersAllowedToPlay")
                        .HasColumnType("int");

                    b.Property<int>("MinimumPlayersAllowedToPlay")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PriceInShop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Boardgames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppropriateAge = 14,
                            AveragePlayingTime = 90,
                            CardImageUrl = "/assets/games/Dune_Imperium_card.jpg",
                            Description = "Dune: Imperium is a game that uses deck-building to add a hidden-information angle to traditional worker placement. It finds inspiration in elements and characters from the Dune legacy, both the new film from Legendary Pictures and the seminal literary series from Frank Herbert, Brian Herbert, and Kevin J.Anderson.As a leader of one of the Great Houses of the Landsraad, raise your banner and marshal your forces and spies. War is coming, and at the center of the conflict is Arrakis – Dune, the desert planet.",
                            DetailsImageUrl = "/assets/games/Dune_Imperium_details.jpg",
                            Difficulty = 3.0,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 4,
                            MinimumPlayersAllowedToPlay = 1,
                            Name = "Dune: Imperium",
                            PriceInShop = 90.00m,
                            Rating = 3.5,
                            YearPublished = 2020
                        },
                        new
                        {
                            Id = 2,
                            AppropriateAge = 12,
                            AveragePlayingTime = 120,
                            CardImageUrl = "/assets/games/Terraforming_Mars_card.jpg",
                            Description = "In the 2400s, mankind begins to terraform the planet Mars. Giant corporations, sponsored by the World Government on Earth, initiate huge projects to raise the temperature, the oxygen level, and the ocean coverage until the environment is habitable. In Terraforming Mars, you play one of those corporations and work together in the terraforming process, but compete for getting victory points that are awarded not only for your contribution to the terraforming, but also for advancing human infrastructure throughout the solar system, and doing other commendable things.",
                            DetailsImageUrl = "/assets/games/Terraforming_Mars_details.jpg",
                            Difficulty = 3.5,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 4,
                            MinimumPlayersAllowedToPlay = 1,
                            Name = "Terraforming Mars",
                            PriceInShop = 100.00m,
                            Rating = 4.5,
                            YearPublished = 2016
                        },
                        new
                        {
                            Id = 3,
                            AppropriateAge = 10,
                            AveragePlayingTime = 90,
                            CardImageUrl = "/assets/games/Catan_card.jpg",
                            Description = "In CATAN (formerly The Settlers of Catan), players try to be the dominant force on the island of Catan by building settlements, cities, and roads. On each turn dice are rolled to determine what resources the island produces. Players build by spending resources (sheep, wheat, wood, brick and ore) that are depicted by these resource cards; each land type, with the exception of the unproductive desert, produces a specific resource: hills produce brick, forests produce wood, mountains produce ore, fields produce wheat, and pastures produce sheep. CATAN has won multiple awards and is one of the most popular games in recent history due to its amazing ability to appeal to experienced gamers as well as those new to the hobby.",
                            DetailsImageUrl = "/assets/games/Catan_details.jpg",
                            Difficulty = 2.0,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 4,
                            MinimumPlayersAllowedToPlay = 3,
                            Name = "Catan",
                            PriceInShop = 50.00m,
                            Rating = 3.1000000000000001,
                            YearPublished = 1995
                        },
                        new
                        {
                            Id = 4,
                            AppropriateAge = 10,
                            AveragePlayingTime = 60,
                            CardImageUrl = "/assets/games/Photosynthesis_card.jpg",
                            Description = "The sun shines brightly on the canopy of the forest, and the trees use this wonderful energy to grow and develop their beautiful foliage. Sow your crops wisely and the shadows of your growing trees could slow your opponents down, but don't forget that the sun revolves around the forest. Welcome to the world of Photosynthesis, the green strategy board game!",
                            DetailsImageUrl = "/assets/games/Photosynthesis_details.jpg",
                            Difficulty = 2.0,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 4,
                            MinimumPlayersAllowedToPlay = 2,
                            Name = "Photosynthesis",
                            PriceInShop = 45.00m,
                            Rating = 3.7999999999999998,
                            YearPublished = 2017
                        },
                        new
                        {
                            Id = 5,
                            AppropriateAge = 8,
                            AveragePlayingTime = 60,
                            CardImageUrl = "/assets/games/Ticket_To_Ride_card.jpg",
                            Description = "With elegantly simple gameplay, Ticket to Ride can be learned in under 15 minutes. Players collect cards of various types of train cars they then use to claim railway routes in North America. The longer the routes, the more points they earn. Additional points come to those who fulfill Destination Tickets – goal cards that connect distant cities; and to the player who builds the longest continuous route.",
                            DetailsImageUrl = "/assets/games/Ticket_To_Ride_details.jpg",
                            Difficulty = 1.5,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 5,
                            MinimumPlayersAllowedToPlay = 2,
                            Name = "Ticket to Ride",
                            PriceInShop = 70.00m,
                            Rating = 3.5,
                            YearPublished = 2004
                        },
                        new
                        {
                            Id = 6,
                            AppropriateAge = 14,
                            AveragePlayingTime = 120,
                            CardImageUrl = "/assets/games/Gloomhaven_card.jpg",
                            Description = "Gloomhaven is a game of Euro-inspired tactical combat in a persistent world of shifting motives. Players will take on the role of a wandering adventurer with their own special set of skills and their own reasons for traveling to this dark corner of the world. Players must work together out of necessity to clear out menacing dungeons and forgotten ruins. In the process, they will enhance their abilities with experience and loot, discover new locations to explore and plunder, and expand an ever-branching story fueled by the decisions they make. This is a game with a persistent and changing world that is ideally played over many game sessions. After a scenario, players will make decisions on what to do, which will determine how the story continues, kind of like a “Choose Your Own Adventure” book. Playing through a scenario is a cooperative affair where players will fight against automated monsters using an innovative card system to determine the order of play and what a player does on their turn.",
                            DetailsImageUrl = "/assets/games/Gloomhaven_details.jpg",
                            Difficulty = 4.0,
                            IsReserved = false,
                            IsUpcoming = true,
                            MaximumPlayersAllowedToPlay = 4,
                            MinimumPlayersAllowedToPlay = 1,
                            Name = "Gloomhaven",
                            PriceInShop = 250.00m,
                            Rating = 4.7999999999999998,
                            YearPublished = 2017
                        },
                        new
                        {
                            Id = 7,
                            AppropriateAge = 10,
                            AveragePlayingTime = 45,
                            CardImageUrl = "/assets/games/Mysterium_card.jpg",
                            Description = "In the 1920s, Mr. MacDowell, a gifted astrologer, immediately detected a supernatural being upon entering his new house in Scotland. He gathered eminent mediums of his time for an extraordinary séance, and they have seven hours to make contact with the ghost and investigate any clues that it can provide to unlock an old mystery.Unable to talk, the amnesiac ghost communicates with the mediums through visions, which are represented in the game by illustrated cards. The mediums must decipher the images to help the ghost remember how he was murdered: Who did the crime? Where did it take place? Which weapon caused the death? The more the mediums cooperate and guess well, the easier it is to catch the right culprit.",
                            DetailsImageUrl = "/assets/games/Mysterium_details.jpg",
                            Difficulty = 2.0,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 7,
                            MinimumPlayersAllowedToPlay = 2,
                            Name = "Mysterium",
                            PriceInShop = 70.00m,
                            Rating = 2.2999999999999998,
                            YearPublished = 2015
                        },
                        new
                        {
                            Id = 8,
                            AppropriateAge = 10,
                            AveragePlayingTime = 60,
                            CardImageUrl = "/assets/games/Everdell_card.jpg",
                            Description = "Within the charming valley of Everdell, beneath the boughs of towering trees, among meandering streams and mossy hollows, a civilization of forest critters is thriving and expanding. From Everfrost to Bellsong, many a year have come and gone, but the time has come for new territories to be settled and new cities established. You will be the leader of a group of critters intent on just such a task. There are buildings to construct, lively characters to meet, events to host—you have a busy year ahead of yourself. Will the sun shine brightest on your city before the winter moon rises?",
                            DetailsImageUrl = "/assets/games/Everdell_details.jpg",
                            Difficulty = 2.7999999999999998,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 4,
                            MinimumPlayersAllowedToPlay = 1,
                            Name = "Everdell",
                            PriceInShop = 110m,
                            Rating = 4.2999999999999998,
                            YearPublished = 2018
                        },
                        new
                        {
                            Id = 9,
                            AppropriateAge = 8,
                            AveragePlayingTime = 90,
                            CardImageUrl = "/assets/games/Monopoly_Bulgaria_card.jpg",
                            Description = "Know your motherland, to love it. But what if you could own a small part of Bulgaria for yourself? This is possible with the special edition of Monopoly - Bulgaria is wonderful. Buy one of the most majestic sights in our country - the unique Stobski pyramids, the National Palace of Culture, the temple-monument \"St. Alexander Nevsky\". Take a walk along some of our most beautiful hiking trails - go inside Devetashka Cave, cross the Devil's Bridge and connect with nature through the Paneurhythmy around the Seven Rila Lakes. The rules are well known to everyone - build hotels and houses to develop your properties, try your luck with the BANK or CHANCE cards. Roll the dice and discover the wonders of Bulgaria as you fight for victory.",
                            DetailsImageUrl = "/assets/games/Monopoly_Bulgaria_details.jpg",
                            Difficulty = 1.5,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 6,
                            MinimumPlayersAllowedToPlay = 2,
                            Name = "Monopoly-Bulgaria",
                            PriceInShop = 55.00m,
                            Rating = 4.7000000000000002,
                            YearPublished = 2021
                        },
                        new
                        {
                            Id = 10,
                            AppropriateAge = 8,
                            AveragePlayingTime = 45,
                            CardImageUrl = "/assets/games/Pandemic_card.jpg",
                            Description = "In Pandemic, several virulent diseases have broken out simultaneously all over the world! The players are disease-fighting specialists whose mission is to treat disease hotspots while researching cures for each of four plagues before they get out of hand. The game board depicts several major population centers on Earth. On each turn, a player can use up to four actions to travel between cities, treat infected populaces, discover a cure, or build a research station. A deck of cards provides the players with these abilities, but sprinkled throughout this deck are Epidemic! cards that accelerate and intensify the diseases' activity. A second, separate deck of cards controls the \"normal\" spread of the infections.",
                            DetailsImageUrl = "/assets/games/Pandemic_details.jpg",
                            Difficulty = 2.5,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 4,
                            MinimumPlayersAllowedToPlay = 2,
                            Name = "Pandemic",
                            PriceInShop = 45.00m,
                            Rating = 3.3999999999999999,
                            YearPublished = 2008
                        },
                        new
                        {
                            Id = 11,
                            AppropriateAge = 14,
                            AveragePlayingTime = 90,
                            CardImageUrl = "/assets/games/Brass_Birmingham_card.jpg",
                            Description = "Brass: Birmingham is an economic strategy game sequel to Martin Wallace' 2007 masterpiece, Brass. Brass: Birmingham tells the story of competing entrepreneurs in Birmingham during the industrial revolution, between the years of 1770-1870. It offers a very different story arc and experience from its predecessor. As in its predecessor, you must develop, build, and establish your industries and network, in an effort to exploit low or high market demands. The game is played over two halves: the canal era (years 1770-1830) and the rail era (years 1830-1870). To win the game, score the most VPs. VPs are counted at the end of each half for the canals, rails and established (flipped) industry tiles.",
                            DetailsImageUrl = "/assets/games/Brass_Birmingham_details.jpg",
                            Difficulty = 4.0,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 4,
                            MinimumPlayersAllowedToPlay = 2,
                            Name = "Brass: Birmingham",
                            PriceInShop = 150.00m,
                            Rating = 4.7000000000000002,
                            YearPublished = 2018
                        },
                        new
                        {
                            Id = 12,
                            AppropriateAge = 14,
                            AveragePlayingTime = 120,
                            CardImageUrl = "/assets/games/Ark_Nova_card.jpg",
                            Description = "In Ark Nova, you will plan and design a modern, scientifically managed zoo. With the ultimate goal of owning the most successful zoological establishment, you will build enclosures, accommodate animals, and support conservation projects all over the world. Specialists and unique buildings will help you in achieving this goal.\r\nEach player has a set of five action cards to manage their gameplay, and the power of an action is determined by the slot the card currently occupies. The cards in question are:\r\n\r\nCARDS: Allows you to gain new zoo cards (animals, sponsors, and conservation project cards).\r\nBUILD: Allows you to build standard or special enclosures, kiosks, and pavilions.\r\nANIMALS: Allows you to accommodate animals in your zoo.\r\nASSOCIATION: Allows your association workers to carry out different tasks.\r\nSPONSORS: Allows you to play a sponsor card in your zoo or to raise money.\r\n255 cards featuring animals, specialists, special enclosures, and conservation projects, each with a special ability, are at the heart of Ark Nova. Use them to increase the appeal and scientific reputation of your zoo and collect conservation points.",
                            DetailsImageUrl = "/assets/games/Ark_Nova_details.jpg",
                            Difficulty = 3.7000000000000002,
                            IsReserved = false,
                            IsUpcoming = true,
                            MaximumPlayersAllowedToPlay = 4,
                            MinimumPlayersAllowedToPlay = 1,
                            Name = "Ark Nova",
                            PriceInShop = 135.00m,
                            Rating = 4.2000000000000002,
                            YearPublished = 2021
                        },
                        new
                        {
                            Id = 13,
                            AppropriateAge = 14,
                            AveragePlayingTime = 90,
                            CardImageUrl = "/assets/games/Scythe_card.jpg",
                            Description = "It is a time of unrest in 1920s Europa. The ashes from the first great war still darken the snow. The capitalistic city-state known simply as “The Factory”, which fueled the war with heavily armored mechs, has closed its doors, drawing the attention of several nearby countries.\r\nScythe is an engine-building game set in an alternate-history 1920s period. It is a time of farming and war, broken hearts and rusted gears, innovation and valor. In Scythe, each player represents a character from one of five factions of Eastern Europe who are attempting to earn their fortune and claim their faction's stake in the land around the mysterious Factory. Players conquer territory, enlist new recruits, reap resources, gain villagers, build structures, and activate monstrous mechs.",
                            DetailsImageUrl = "/assets/games/Scythe_details.jpg",
                            Difficulty = 3.5,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 5,
                            MinimumPlayersAllowedToPlay = 1,
                            Name = "Scythe",
                            PriceInShop = 165.00m,
                            Rating = 4.0,
                            YearPublished = 2016
                        },
                        new
                        {
                            Id = 14,
                            AppropriateAge = 12,
                            AveragePlayingTime = 150,
                            CardImageUrl = "/assets/games/Nemesis_card.jpg",
                            Description = "Playing Nemesis will take you into the heart of sci-fi survival horror in all its terror. A soldier fires blindly down a corridor, trying to stop the alien advance. A scientist races to find a solution in his makeshift lab. A traitor steals the last escape pod in the very last moment. Intruders you meet on the ship are not only reacting to the noise you make but also evolve as the time goes by. The longer the game takes, the stronger they become. During the game, you control one of the crew members with a unique set of skills, personal deck of cards, and individual starting equipment. These heroes cover all your basic SF horror needs. For example, the scientist is great with computers and research, but will have a hard time in combat. The soldier, on the other hand...",
                            DetailsImageUrl = "/assets/games/Nemesis_details.jpg",
                            Difficulty = 3.5,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 5,
                            MinimumPlayersAllowedToPlay = 1,
                            Name = "Nemesis",
                            PriceInShop = 200.00m,
                            Rating = 4.7000000000000002,
                            YearPublished = 2018
                        },
                        new
                        {
                            Id = 15,
                            AppropriateAge = 10,
                            AveragePlayingTime = 60,
                            CardImageUrl = "/assets/games/Wingspan_card.jpg",
                            Description = "Wingspan is a competitive, medium-weight, card-driven, engine-building board game from Stonemaier Games. It's designed by Elizabeth Hargrave and features over 170 birds illustrated by Beth Sobel, Natalia Rojas, and Ana Maria Martinez.\r\n\r\nYou are bird enthusiasts—researchers, bird watchers, ornithologists, and collectors—seeking to discover and attract the best birds to your network of wildlife preserves. Each bird extends a chain of powerful combinations in one of your habitats (actions). These habitats focus on several key aspects of growth:\r\n\r\nGain food tokens via custom dice in a birdfeeder dice tower\r\nLay eggs using egg miniatures in a variety of colors\r\nDraw from hundreds of unique bird cards and play them\r\nThe winner is the player with the most points after 4 rounds.",
                            DetailsImageUrl = "/assets/games/Wingspan_details.jpg",
                            Difficulty = 2.5,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 5,
                            MinimumPlayersAllowedToPlay = 1,
                            Name = "Wingspan",
                            PriceInShop = 100.00m,
                            Rating = 3.5,
                            YearPublished = 2019
                        },
                        new
                        {
                            Id = 16,
                            AppropriateAge = 10,
                            AveragePlayingTime = 45,
                            CardImageUrl = "/assets/games/Cascadia_card.jpg",
                            Description = "Cascadia is a puzzly tile-laying and token-drafting game featuring the habitats and wildlife of the Pacific Northwest.\r\n\r\nIn the game, you take turns building out your own terrain area and populating it with wildlife. You start with three hexagonal habitat tiles (with the five types of habitat in the game), and on a turn you choose a new habitat tile that's paired with a wildlife token, then place that tile next to your other ones and place the wildlife token on an appropriate habitat. (Each tile depicts 1-3 types of wildlife from the five types in the game, and you can place at most one tile on a habitat.) Four tiles are on display, with each tile being paired at random with a wildlife token, so you must make the best of what's available — unless you have a nature token to spend so that you can pick your choice of each item.",
                            DetailsImageUrl = "/assets/games/Cascadia_details.jpg",
                            Difficulty = 1.5,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 4,
                            MinimumPlayersAllowedToPlay = 1,
                            Name = "Cascadia",
                            PriceInShop = 72.00m,
                            Rating = 2.8999999999999999,
                            YearPublished = 2021
                        },
                        new
                        {
                            Id = 17,
                            AppropriateAge = 14,
                            AveragePlayingTime = 15,
                            CardImageUrl = "/assets/games/Codenames_card.jpg",
                            Description = "Two rival spymasters know the secret identities of 25 agents. Their teammates know the agents only by their codenames — single-word labels like \"disease\", \"Germany\", and \"carrot\". Yes, carrot. It's a legitimate codename. Each spymaster wants their team to identify their agents first...without uncovering the assassin by mistake.\r\n\r\nIn Codenames, two teams compete to see who can make contact with all of their agents first. Lay out 25 cards, each bearing a single word. The spymasters look at a card showing the identity of each card, then take turns clueing their teammates. A clue consists of a single word and a number, with the number suggesting how many cards in play have some association to the given clue word. The teammates then identify one agent they think is on their team; if they're correct, they can keep guessing up to the stated number of times; if the agent belongs to the opposing team or is an innocent bystander, the team's turn ends; and if they fingered the assassin, they lose the game.\r\n\r\nSpymasters continue giving clues until one team has identified all of their agents or the assassin has removed one team from play.",
                            DetailsImageUrl = "/assets/games/Codenames_details.jpg",
                            Difficulty = 1.0,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 8,
                            MinimumPlayersAllowedToPlay = 2,
                            Name = "Codenames",
                            PriceInShop = 40.00m,
                            Rating = 4.2999999999999998,
                            YearPublished = 2015
                        },
                        new
                        {
                            Id = 18,
                            AppropriateAge = 8,
                            AveragePlayingTime = 30,
                            CardImageUrl = "/assets/games/Dixit_card.jpg",
                            Description = "Each turn in Dixit, one player is the storyteller, chooses one of the six cards in their hand, then makes up a sentence based on that card's image and says it out loud without showing the card to the other players. Each other player then selects the card in their hand that best matches the sentence and gives the selected card to the storyteller, without showing it to anyone else.\r\n\r\nThe storyteller shuffles their card with all of the received cards, then reveals all of these cards. Each player other than the storyteller then secretly guesses which card belongs to the storyteller. If nobody or everybody guesses the correct card, the storyteller scores 0 points, and each other player scores 2 points. Otherwise, the storyteller and whoever found the correct answer score 3 points. Additionally, the non-storyteller players score 1 point for every vote received by their card.\r\n\r\nThe game ends when the deck is empty or if a player has scored at least 30 points. In either case, the player with the most points wins.\r\n\r\nThe Dixit base game and each expansion contains 84 cards, and the cards can be mixed together as desired.",
                            DetailsImageUrl = "/assets/games/Dixit_details.jpg",
                            Difficulty = 1.2,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 8,
                            MinimumPlayersAllowedToPlay = 3,
                            Name = "Dixit",
                            PriceInShop = 55.00m,
                            Rating = 3.1000000000000001,
                            YearPublished = 2008
                        },
                        new
                        {
                            Id = 19,
                            AppropriateAge = 7,
                            AveragePlayingTime = 15,
                            CardImageUrl = "/assets/games/Exlpoding_Kittens_card.jpg",
                            Description = "Exploding Kittens is a kitty-powered version of Russian Roulette. Players take turns drawing cards until someone draws an exploding kitten and loses the game. The deck is made up of cards that let you avoid exploding by peeking at cards before you draw, forcing your opponent to draw multiple cards, or shuffling the deck.\r\n\r\nThe game gets more and more intense with each card you draw because fewer cards left in the deck means a greater chance of drawing the kitten and exploding in a fiery ball of feline hyperbole.",
                            DetailsImageUrl = "/assets/games/Exlpoding_Kittens_details.jpg",
                            Difficulty = 1.0,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 5,
                            MinimumPlayersAllowedToPlay = 2,
                            Name = "Exploding Kittens",
                            PriceInShop = 45.00m,
                            Rating = 3.5,
                            YearPublished = 2015
                        },
                        new
                        {
                            Id = 20,
                            AppropriateAge = 12,
                            AveragePlayingTime = 30,
                            CardImageUrl = "/assets/games/Decrypto_card.jpg",
                            Description = "Players compete in two teams in Decrypto, with each trying to correctly interpret the coded messages presented to them by their teammates while cracking the codes they intercept from the opposing team.\r\n\r\nIn more detail, each team has their own screen, and in this screen they tuck four cards in pockets numbered 1-4, letting everyone on the same team see the words on these cards while hiding the words from the opposing team. In the first round, each team does the following: One team member takes a code card that shows three of the digits 1-4 in some order, e.g., 4-2-1. They then give a coded message that their teammates must use to guess this code. For example, if the team's four words are \"pig\", \"candy\", \"tent\", and \"son\", then I might say \"Sam-striped-pink\" and hope that my teammates can correctly map those words to 4-2-1. If they guess correctly, great; if not, we receive a black mark of failure.",
                            DetailsImageUrl = "/assets/games/Decrypto_details.jpg",
                            Difficulty = 1.8,
                            IsReserved = false,
                            IsUpcoming = false,
                            MaximumPlayersAllowedToPlay = 8,
                            MinimumPlayersAllowedToPlay = 3,
                            Name = "Decrypto",
                            PriceInShop = 40.00m,
                            Rating = 3.6000000000000001,
                            YearPublished = 2018
                        },
                        new
                        {
                            Id = 21,
                            AppropriateAge = 14,
                            AveragePlayingTime = 150,
                            CardImageUrl = "/assets/games/Eclipse_card.jpg",
                            Description = "A game of Eclipse places you in control of a vast interstellar civilization, competing for success with its rivals. You explore new star systems, research technologies, and build spaceships with which to wage war. There are many potential paths to victory, so you need to plan your strategy according to the strengths and weaknesses of your species, while paying attention to the other civilizations' endeavors.\r\n\r\nEclipse: Second Dawn for the Galaxy is a revised and upgraded version of the Eclipse base game that debuted in 2011 that features:\r\n\r\nNew graphic design, while maintaining the acclaimed symbology of the first edition\r\nA full line of Ship Pack 1 miniatures\r\nNew miniatures for ancients, GCDS, orbitals, and more\r\nCustom plastic inlays\r\nCustom combat dice\r\nFine-tuned gameplay",
                            DetailsImageUrl = "/assets/games/Eclipse_details.jpg",
                            Difficulty = 3.7000000000000002,
                            IsReserved = false,
                            IsUpcoming = true,
                            MaximumPlayersAllowedToPlay = 6,
                            MinimumPlayersAllowedToPlay = 2,
                            Name = "Eclipse: Second Dawn for the Galaxy",
                            PriceInShop = 275.00m,
                            Rating = 4.2999999999999998,
                            YearPublished = 2020
                        });
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.BoardgameGenre", b =>
                {
                    b.Property<int>("BoardgameId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("BoardgameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("BoardgamesGenres");

                    b.HasData(
                        new
                        {
                            BoardgameId = 1,
                            GenreId = 17
                        },
                        new
                        {
                            BoardgameId = 1,
                            GenreId = 13
                        },
                        new
                        {
                            BoardgameId = 1,
                            GenreId = 12
                        },
                        new
                        {
                            BoardgameId = 2,
                            GenreId = 10
                        },
                        new
                        {
                            BoardgameId = 2,
                            GenreId = 8
                        },
                        new
                        {
                            BoardgameId = 2,
                            GenreId = 9
                        },
                        new
                        {
                            BoardgameId = 3,
                            GenreId = 18
                        },
                        new
                        {
                            BoardgameId = 3,
                            GenreId = 10
                        },
                        new
                        {
                            BoardgameId = 4,
                            GenreId = 1
                        },
                        new
                        {
                            BoardgameId = 4,
                            GenreId = 10
                        },
                        new
                        {
                            BoardgameId = 5,
                            GenreId = 19
                        },
                        new
                        {
                            BoardgameId = 6,
                            GenreId = 2
                        },
                        new
                        {
                            BoardgameId = 6,
                            GenreId = 6
                        },
                        new
                        {
                            BoardgameId = 6,
                            GenreId = 15
                        },
                        new
                        {
                            BoardgameId = 6,
                            GenreId = 14
                        },
                        new
                        {
                            BoardgameId = 7,
                            GenreId = 3
                        },
                        new
                        {
                            BoardgameId = 7,
                            GenreId = 7
                        },
                        new
                        {
                            BoardgameId = 7,
                            GenreId = 16
                        },
                        new
                        {
                            BoardgameId = 8,
                            GenreId = 20
                        },
                        new
                        {
                            BoardgameId = 8,
                            GenreId = 21
                        },
                        new
                        {
                            BoardgameId = 8,
                            GenreId = 9
                        },
                        new
                        {
                            BoardgameId = 9,
                            GenreId = 18
                        },
                        new
                        {
                            BoardgameId = 9,
                            GenreId = 10
                        },
                        new
                        {
                            BoardgameId = 10,
                            GenreId = 13
                        },
                        new
                        {
                            BoardgameId = 10,
                            GenreId = 14
                        },
                        new
                        {
                            BoardgameId = 11,
                            GenreId = 10
                        },
                        new
                        {
                            BoardgameId = 11,
                            GenreId = 8
                        },
                        new
                        {
                            BoardgameId = 11,
                            GenreId = 19
                        },
                        new
                        {
                            BoardgameId = 12,
                            GenreId = 20
                        },
                        new
                        {
                            BoardgameId = 12,
                            GenreId = 10
                        },
                        new
                        {
                            BoardgameId = 12,
                            GenreId = 22
                        },
                        new
                        {
                            BoardgameId = 13,
                            GenreId = 9
                        },
                        new
                        {
                            BoardgameId = 13,
                            GenreId = 10
                        },
                        new
                        {
                            BoardgameId = 14,
                            GenreId = 2
                        },
                        new
                        {
                            BoardgameId = 14,
                            GenreId = 7
                        },
                        new
                        {
                            BoardgameId = 14,
                            GenreId = 14
                        },
                        new
                        {
                            BoardgameId = 15,
                            GenreId = 20
                        },
                        new
                        {
                            BoardgameId = 15,
                            GenreId = 21
                        },
                        new
                        {
                            BoardgameId = 15,
                            GenreId = 23
                        },
                        new
                        {
                            BoardgameId = 16,
                            GenreId = 20
                        },
                        new
                        {
                            BoardgameId = 16,
                            GenreId = 22
                        },
                        new
                        {
                            BoardgameId = 16,
                            GenreId = 11
                        },
                        new
                        {
                            BoardgameId = 17,
                            GenreId = 21
                        },
                        new
                        {
                            BoardgameId = 17,
                            GenreId = 16
                        },
                        new
                        {
                            BoardgameId = 17,
                            GenreId = 3
                        },
                        new
                        {
                            BoardgameId = 18,
                            GenreId = 21
                        },
                        new
                        {
                            BoardgameId = 18,
                            GenreId = 16
                        },
                        new
                        {
                            BoardgameId = 19,
                            GenreId = 20
                        },
                        new
                        {
                            BoardgameId = 19,
                            GenreId = 21
                        },
                        new
                        {
                            BoardgameId = 20,
                            GenreId = 3
                        },
                        new
                        {
                            BoardgameId = 20,
                            GenreId = 16
                        },
                        new
                        {
                            BoardgameId = 21,
                            GenreId = 6
                        },
                        new
                        {
                            BoardgameId = 21,
                            GenreId = 24
                        });
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.GameReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BoardGameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewOwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("BoardGameId");

                    b.HasIndex("ReviewOwnerId");

                    b.ToTable("GameReviews");
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Abstract"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Deduction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dexterity"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Exploration"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Industry"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Territory building"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Economy"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Deckbuilder"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Placement"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Cooperative"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Combat"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Party"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Negotiation"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Trains"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Animals"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Card game"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Environmental"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Educational"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Civilization"
                        });
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.PlaceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PlaceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            Name = "Small table",
                            PricePerHour = 10.00m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 4,
                            Name = "Medium table",
                            PricePerHour = 20.00m
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 10,
                            Name = "Large table",
                            PricePerHour = 50.00m
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 60,
                            Name = "Whole place",
                            PricePerHour = 300.00m
                        });
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdditionalComment")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservationOwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationOwnerId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.ReservationPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaceTypeId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationPlaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsReserved = false,
                            Name = "Table for 2 - No1",
                            PlaceTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsReserved = false,
                            Name = "Table for 2 - No2",
                            PlaceTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsReserved = false,
                            Name = "Table for 2 - No3",
                            PlaceTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsReserved = false,
                            Name = "Table for 2 - No4",
                            PlaceTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            IsReserved = false,
                            Name = "Table for 4 - No1",
                            PlaceTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            IsReserved = false,
                            Name = "Table for 4 - No2",
                            PlaceTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            IsReserved = false,
                            Name = "Table for 4 - No3",
                            PlaceTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            IsReserved = false,
                            Name = "Table for 4 - No4",
                            PlaceTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            IsReserved = false,
                            Name = "Table for 4 - No5",
                            PlaceTypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            IsReserved = false,
                            Name = "Table for 4 - No6",
                            PlaceTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            IsReserved = false,
                            Name = "Table for 4 - No7",
                            PlaceTypeId = 2
                        },
                        new
                        {
                            Id = 12,
                            IsReserved = false,
                            Name = "Table for 4 - No8",
                            PlaceTypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            IsReserved = false,
                            Name = "Table for 10 - No1",
                            PlaceTypeId = 3
                        },
                        new
                        {
                            Id = 14,
                            IsReserved = false,
                            Name = "Table for 10 - No2",
                            PlaceTypeId = 3
                        },
                        new
                        {
                            Id = 15,
                            IsReserved = false,
                            Name = "Whole place",
                            PlaceTypeId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.Boardgame", b =>
                {
                    b.HasOne("BoardGameHub.Data.Data.DataModels.Reservation", "Reservation")
                        .WithMany("BoardgamesReserved")
                        .HasForeignKey("ReservationId");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.BoardgameGenre", b =>
                {
                    b.HasOne("BoardGameHub.Data.Data.DataModels.Boardgame", "Boardgame")
                        .WithMany("BoardgamesGenres")
                        .HasForeignKey("BoardgameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameHub.Data.Data.DataModels.Genre", "Genre")
                        .WithMany("BoardgamesGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boardgame");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.GameReview", b =>
                {
                    b.HasOne("BoardGameHub.Data.Data.DataModels.Boardgame", "Boardgame")
                        .WithMany("GameReviews")
                        .HasForeignKey("BoardGameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BoardGameHub.Data.Data.DataModels.ApplicationUser", "ReviewOwner")
                        .WithMany("GameReviews")
                        .HasForeignKey("ReviewOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boardgame");

                    b.Navigation("ReviewOwner");
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.Reservation", b =>
                {
                    b.HasOne("BoardGameHub.Data.Data.DataModels.ApplicationUser", "ReservationOwner")
                        .WithMany()
                        .HasForeignKey("ReservationOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservationOwner");
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.ReservationPlace", b =>
                {
                    b.HasOne("BoardGameHub.Data.Data.DataModels.PlaceType", "PlaceType")
                        .WithMany()
                        .HasForeignKey("PlaceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameHub.Data.Data.DataModels.Reservation", "Reservation")
                        .WithMany("ReservationPlaces")
                        .HasForeignKey("ReservationId");

                    b.Navigation("PlaceType");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BoardGameHub.Data.Data.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BoardGameHub.Data.Data.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameHub.Data.Data.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BoardGameHub.Data.Data.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.ApplicationUser", b =>
                {
                    b.Navigation("GameReviews");
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.Boardgame", b =>
                {
                    b.Navigation("BoardgamesGenres");

                    b.Navigation("GameReviews");
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.Genre", b =>
                {
                    b.Navigation("BoardgamesGenres");
                });

            modelBuilder.Entity("BoardGameHub.Data.Data.DataModels.Reservation", b =>
                {
                    b.Navigation("BoardgamesReserved");

                    b.Navigation("ReservationPlaces");
                });
#pragma warning restore 612, 618
        }
    }
}
